Fix wrong mutable borrow on refcell. (#990)
Fix crash on wrong mutable borrow on refcell: https://app.circleci.com/pipelines/github/RedisGears/RedisGears/4479/workflows/cdeb1ff7-6918-47cd-81ab-02661be041f5/jobs/12005

```
2124:M 18 Jul 2023 12:06:51.465 # <redisgears_2> Application panicked, panicked at 'already borrowed: BorrowMutError', redisgears_core/src/keys_notifications.rs:118:48


------ MODULES INFO OUTPUT ------
# redisgears_2_trace
redisgears_2_trace:   0: redis_module::base_info_func
             at /root/.cargo/git/checkouts/redismodule-rs-db21e74d646195ef/4e9ccd7/src/lib.rs:68:33
   1: redisgears::gears_module::__info_func
             at /root/.cargo/git/checkouts/redismodule-rs-db21e74d646195ef/4e9ccd7/src/macros.rs:166:13
   2: modulesCollectInfo
             at /home/runner/work/redis-stack/redis-stack/redis/src/module.c:10293:9
   3: logModulesInfo
             at /home/runner/work/redis-stack/redis-stack/redis/src/debug.c:1900:22
      printCrashReport
             at /home/runner/work/redis-stack/redis-stack/redis/src/debug.c:2183:5
   4: _serverAssert
             at /home/runner/work/redis-stack/redis-stack/redis/src/debug.c:1062:9
   5: redisgears::js_init::{{closure}}
             at /build/redisgears_core/src/lib.rs:902:13
   6: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/alloc/src/boxed.rs:1999:9
      std::panicking::rust_panic_with_hook
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:709:13
   7: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:597:13
   8: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:151:18
   9: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
  10: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
  11: core::result::unwrap_failed
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1651:5
  12: core::result::Result<T,E>::expect
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1033:23
  13: core::cell::RefCell<T>::borrow_mut
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/cell.rs:1017:9
  14: redisgears::keys_notifications::fire_event::{{closure}}
             at /build/redisgears_core/src/keys_notifications.rs:118:29
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
  16: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/alloc/src/boxed.rs:1985:9
  17: redisgears_v8_plugin::v8_notifications_ctx::V8NotificationsCtxInternal::run_sync::{{closure}}
             at /build/redisgears_v8_plugin/src/v8_notifications_ctx.rs:68:33
  18: redisgears_v8_plugin::v8_script_ctx::V8ScriptCtx::promise_rejected_or_fulfilled_async::{{closure}}::{{closure}}::{{closure}}
             at /build/redisgears_v8_plugin/src/v8_script_ctx.rs:379:21
  19: core::option::Option<T>::map
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:1075:29
  20: redisgears_v8_plugin::v8_script_ctx::V8ScriptCtx::promise_rejected_or_fulfilled_async::{{closure}}::{{closure}}
             at /build/redisgears_v8_plugin/src/v8_script_ctx.rs:373:17
  21: redisgears_v8_plugin::v8_script_ctx::V8ScriptCtx::promise_rejected_or_fulfilled_async::{{closure}}
             at /build/redisgears_v8_plugin/src/v8_script_ctx.rs:370:52
  22: v8_rs::v8::v8_native_function_template::native_basic_function
             at /root/.cargo/git/checkouts/v8-rs-e9222db4c6234a10/e9e6fa1/src/v8/v8_native_function_template.rs:89:15
  23: v8_NativeBaseFunction
             at /root/.cargo/git/checkouts/v8-rs-e9222db4c6234a10/e9e6fa1/v8_c_api/src/v8_c_api.cpp:619:35
  24: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
  25: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
  26: Builtins_CEntry_Return1_ArgvOnStack_BuiltinExit
```

The crash happened because the stats data of the key space notification are protected by the Redis GIL. So each time, before updating the stats, we must make sure the Redis GIL is held. This was violated on the ack callback in case we call it from a background promise resolving, the caller in this case did not lock the GIL before calling the ack callback.

This PR fixes the violation but in general this is very fragile and should be fixed in a more robust way that will prevent such mistakes in the future. Open an [issue](https://github.com/RedisGears/RedisGears/issues/991) to remove all usages of `refcell` and use `RedisGILGuard` instead which better guard object protected by GIL and does not allow to touch them without providing a `RedisLockIndicator`.